/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lenzhoundmusher.panels;

import java.util.ArrayList;
import jssc.SerialPort;
import lenzhoundmusher.MotorController;
import lenzhoundmusher.Musher;
import lenzhoundmusher.SerialWorker;

/**
 *
 * @author Thayer
 */
public class SearchPanel extends javax.swing.JPanel {

    /**
     * Creates new form SearchPanel
     * @param callback
     */
    public SearchPanel(Musher callback) {
        initComponents();
        searchingProgressBar.setIndeterminate(true);
        Thread t = new Thread(() -> {
            boolean addAPeriod = true;
            while(returnPort == null){
                ArrayList<SerialPort> motors = SerialWorker.findMotors();
                
                if(addAPeriod){
                    promptLabel.setText(promptLabel.getText() + '.');
                    addAPeriod = false;
                }else{
                    promptLabel.setText(promptLabel.getText().substring(0, promptLabel.getText().length() - 1));
                    addAPeriod = true;
                }
                
                if(motors.size()>0){
                    returnPort = motors.get(0);
                    continue;
                }
                try{
                    Thread.sleep(500);
                }catch(Exception e){
                    System.out.println(e);
                }
            }            
            callback.removePanel(this);
            callback.addMotorController(returnPort);
            MotorController.addInUse(returnPort.getPortName());
        });
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchingProgressBar = new javax.swing.JProgressBar();
        promptLabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(401, 132));

        promptLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        promptLabel.setText("     Searching for device. . ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchingProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(promptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 79, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(searchingProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(promptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    SerialPort returnPort = null;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel promptLabel;
    private javax.swing.JProgressBar searchingProgressBar;
    // End of variables declaration//GEN-END:variables
}
